name: highlevel_assignment
description: Potato timer assignment from HighLevel

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

  flutter_mobx: ^2.0.6+1
  freezed_annotation: ^2.0.3
  mobx: ^2.0.7
  provider: ^6.0.3
  hive: ^2.2.1
  get_it: ^7.2.0
  path_provider: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7
  freezed: ^2.0.3+1
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
